---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-init
        image: homura69/musiccloud:latest
        command: ["python", "init_data.py"]
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: POSTGRES_USER
            value: "santiago"
          - name: POSTGRES_PASSWORD
            value: "santiago"
          - name: POSTGRES_DB
            value: "musiccloud"
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_PORT
            value: "5432"