version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=santiago
      - POSTGRES_PASSWORD=santiago
      - POSTGRES_DB=musiccloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U santiago -d musiccloud"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python init_data.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://santiago:santiago@db:5432/musiccloud
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

volumes:
  pgdata:
