# web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: santiago/musiccloud:latest
          env:
            - name: ENVIRONMENT
              value: "production"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort   # o LoadBalancer si usas cloud
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080   # accedes en http://<node-ip>:30080
  selector:
    app: web
