---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: homura69/musiccloud-web:latest
          command: ["/bin/bash", "-c"]
          args: ["python init_data.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: DATABASE_URL
              value: "postgresql://santiago:santiago@postgres:5432/musiccloud"
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m      # 0.1 CPU
              memory: 128Mi  # memoria mínima reservada
            limits:
              cpu: 200m      # hasta 0.2 CPU
              memory: 256Mi  # límite máximo de memoria
